//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ncu.mao.Web.t_privilege {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtprivilegeid;
		protected global::System.Web.UI.WebControls.TextBox txtprivilegename;
		protected global::System.Web.UI.WebControls.TextBox txtdiscription;
		protected global::System.Web.UI.WebControls.TextBox txturl;
		protected global::System.Web.UI.WebControls.CheckBox chkflag;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
